### ISSUE TITLE
tini does not support cmd /sbin/init

### ISSUE THREAD

**Issue by KevinTHU** [krallin/tini#102]
if we run a centos6 container with cmd /sbin/int in docker-ce 17.06.2 with --init, the container will start fail with error logs "init: missing runlevel
Try `init --help' for more information.
"
and we add runlevel like 3, it also can not start by error logs "init: Failed to connect to socket /com/ubuntu/upstart: Connection refused
"
but if we run it in a lower docker version like 1.12.6 without --init, it is ok to run the same images above.

**Comment by krallin** [comment]
On CnetOS 6, `/sbin/init` is Upstart. Upstart is a init system and as such it expects to be running as PID 1. In particular, see this message from `/sbin/init --help`:

```
This daemon is normally executed by the kernel and given process id 1 to denote
its special status.  When executed by a user process, it will actually run
/sbin/telinit.
```

So, when you start Upstart using Tini, it's not running as PID 1, so instead of starting Upstart, it tries to run `telinit`, which is used to _send messages to Upstart_. Obviously, that fails, because Upstart isn't running.

Taking a step back, using Tini to start Upstart is probably not what you want to be doing. Tini is a minimal init system, designed for cases where you don't want to run a full-blown init system like Upstart. If you actually want to run to be running a full-blown init system, then just don't using Tini to start it.

Cheers,

**Comment by KevinTHU** [comment]
@krallin thank you for your help, I think maybe I need to amend the image, using /sbin/init is really not what should be done in docker container. But BTW, I have been using --init for dockerd, could I run a container without Tini?I don't see the method in docker docs. I think the parameter for '--init false' is needed maybe for docker run~

**Comment by krallin** [comment]
You can just leave the `--init` flag out to run without Tini

**Comment by krallin** [comment]
> I think maybe I need to amend the image, using /sbin/init is really not what should be done in docker container.

Indeed, that's why Tini exists 😄 

> could I run a container without Tini?

You can leave out the `--init` flag to do so.

**Comment by KevinTHU** [comment]
> You can leave out the --init flag to do so.
In our environment, most contianer need tini, using '--init' for dockerd is a easy way to make sure every container is running with tini. but maybe some containers don't need tini or should not use tini, it's a little awkward for us, of cause this is not a common situation, hope better to have it^_^.
