### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by wohali** [krallin/tini#103]
Hi there, maintainer of the Apache CouchDB Dockerfiles. Recently, while trying to update our official image Dockerfile, we got some feedback from @tianon that the approach in your README is sub-optimal. See: https://github.com/apache/couchdb-docker/pull/28#discussion_r140907707

Would you consider updating your official installation recommendation so that we don't fall afoul of these guidelines in the future?

**Comment by krallin** [comment]
The reason these are the installation instructions is because they work for practically any possible Docker image (i.e. any image with `chmod` can use them), whereas one-layer installs require having some dependencies pre-installed, or installing them inline (which is what @tianon did in the code he provided you with), which is inevitably distro-specific.

In other words, `ADD` is a little more convenient for users just trying to get this into their image, and `RUN` is a much superior approach (in fact, that's how I install Tini in my own images where I use it) when build performance and a minimal number of layers are desirable.

In the README, I'm trying to optimize for users who want to just get Tini up and running, which is why `ADD` should (I think) remain the default installation method (but I will consider adding `RUN` + `curl` method).

Ultimately, different users have different use cases, and I'm afraid the very first paragraph of the README can't be expected to satisfy all of them. I'm truly sorry here, but as the maintainer for an official Docker image, you probably owe it to yourself and your users to understand these nuances.

---

As an aside, feedback like this is always a little difficult to swallow as an OSS maintainer:

> It sure would be nice if official documentation for projects followed best practices for the communities in which they operate. :( I don't know who to trust at this point.
 
Thanks for your time.

**Comment by wohali** [comment]
@krallin Thanks for the info and for considering the implications for our community.

As an aside, I'm sorry for releasing that frustration at you. I find the entire Docker platform puzzling and frustrating, and am supporting the images for our community out of necessity, not desire. No personal offence was intended; I just wish there was a best practices guide around the whole "understanding graph drivers and the implications for your image" portion that drove the change to our image. I am also an OSS maintainer, for over 22 years now...I know how hard it can be to do the right thing for as many people as often as possible.

Best regards.

**Comment by krallin** [comment]
Thanks for following up @wohali, I very much appreciate it. Wish you best with your Docker image maintenance :)
