### ISSUE TITLE
Signal handling

### ISSUE THREAD

**Issue by M4rotte** [krallin/tini#104]
Hi,

I’m currently testing Tini and there is something I don’t understand regarding signals. I set a minimal Docker image to expose the problem I have. The image runs tini as entrypoint, tini’s getting /entrypoint (a shell script) as first argument. The image is built on top of alpine:3.6, the tini version implied is the one packaged in the distribution (0.14.0).

I’m trying to understand how the signals are handled, the basic need is being to be able to gracefuly stop a MariaDB container. It implies sending a SIGTERM to the mysqld process, so I’d like to send this signal if the container receives SIGABRT or SIGQUIT or whatever… In fact, only SIGKILL should stop the container without trying to cleanly close the MariaDB daemon.

This is the relevant parts of my Dockerfile:

    COPY entrypoint /entrypoint

    WORKDIR /
    USER root
    ENTRYPOINT ["/sbin/tini","-g","-vvv","--","/entrypoint"]

and this is my entrypoint script:

```
#!/bin/sh

trap_t1()  { echo SIGHUP  trapped; }
trap_t2()  { echo SIGINT  trapped; }
trap_t6()  { echo SIGABRT trapped; }
trap_t15() { echo SIGTERM trapped; }

trap trap_t1 1
trap trap_t2 2
trap trap_t6 6
trap trap_t15 15

tail -f /dev/null
```

1) The signal seems to be passed only for SIG{INT,HUP,TERM}. When sending SIGABRT (using `docker kill -s SIGABRT <container name>` or the kill command from within the container) nothing happens. Why ?

2) If I start the container with the help of `docker-compose up` and then issue a Ctrl+C in the terminal the container stops but I can’t see the message that my trap target function "trap_t2" is supposed to echo. This is surprising. I was expecting a SIGINT to be sent to the container, and then passed to the entrypoint script, so it would call "trap_t2"

3) When I add a mysqld process, if I try to issue a `kill -15 <pid of mysqld>` in "trap_t2" it’s like the mysqld received another signal first (SIGINT or SIGQUIT) and so is already stopped and doesn’t receive this SIGTERM

Have a nice day.

**Comment by krallin** [comment]
Hi there,

> 1) The signal seems to be passed only for SIG{INT,HUP,TERM}. When sending SIGABRT (using `docker kill -s SIGABRT <container name>` or the kill command from within the container) nothing happens. Why ?

SIGABRT is intentionally not forwarded, because it's not  a signal other people are supposed to send to your process (it's a signal processes are supposed to send to themselves) to abort.

There is a list of such signals here: https://github.com/krallin/tini/blob/0effd37412ba5ae7e00af0db1f36f5dbc1671df9/src/tini.c#L356

> 2) If I start the container with the help of `docker-compose up` and then issue a Ctrl+C in the terminal the container stops but I can’t see the message that my trap target function "trap_t2" is supposed to echo. This is surprising. I was expecting a SIGINT to be sent to the container, and then passed to the entrypoint script, so it would call "trap_t2"

I'm guessing `docker-compose` is the one handling the signal here. I'm not certain what `docker-compose` does when it receives SIGINT, but there's no reason to think it passes it straight to your containers.

>  3) When I add a mysqld process, if I try to issue a `kill -15 <pid of mysqld>` in "trap_t2" it’s like the mysqld received another signal first (SIGINT or SIGQUIT) and so is already stopped and doesn’t receive this SIGTERM

That's because you're running Tini in process group mode (the `-g` flag you included), so all the children processes receive the signal when it's forwarded (so, that includes MySQL in your case). If you don't want that, you shouldn't use the `-g` flag :)

---

As an aside, it's not very useful to use Tini in front of a shell script that listens for signals (you might as well not use Tini at all in your example, and it wouldn't make a difference).

That said, since your goal is signal rewriting here, I would recommend using a minimal init system that implements that (Tini does not, because it's intentionally minimal). https://github.com/Yelp/dumb-init is one such init system — for your use case, you should probably use that instead of Tini + your shell script.

**Comment by M4rotte** [comment]
Many thx for your (very prompt) answer, it’s a lot more clear to me now (I should have look at the source myself…).

> you might as well not use Tini at all in your example, and it wouldn't make a difference

Yes. The only thing which is different, if I’m not mistaken, is that tini here would reap any zombie process, what the shell script alone wouldn’t do by itself. Am I right?

In addition, I think programs like MariaDB have only a very very few probability to produce zombie processes, so I could probably even directly have mysqld as entrypoint…

I’ll have a look to dumb-init

**Comment by krallin** [comment]
> Yes. The only thing which is different, if I’m not mistaken, is that tini here would reap any zombie process, what the shell script alone wouldn’t do by itself. Am I right?

Bash actually reaps zombies out of the box as well :smile: What it does *not* do by default is forward signals, but if you're writing a bash script to forward signals, then you're pretty much at feature parity with Tini ;) 

Cheers,
