### ISSUE TITLE
GPG key is not certified?

### ISSUE THREAD

**Issue by jwmarshall** [krallin/tini#112]
When trying to verify `tini` binaries with your signature:

```
gpg: requesting key 0527A9B7 from hkp server p80.pool.sks-keyservers.net
gpg: key 7001A4E5: public key "Thomas Orozco <thomas@orozco.fr>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: Signature made Sun Feb 18 16:33:43 2018 UTC using RSA key ID 0527A9B7
gpg: Good signature from "Thomas Orozco <thomas@orozco.fr>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 6380 DC42 8747 F6C3 93FE  ACA5 9A84 159D 7001 A4E5
     Subkey fingerprint: 595E 85A6 B1B4 779E A4DA  AEC7 0B58 8DFF 0527 A9B7
```

**Comment by jwmarshall** [comment]
Nevermind I guess this is a common thing.

**Comment by jcberthon** [comment]
Hi @jwmarshall 

This is not a "common thing" :-)

What gpg is trying to tell you (and I agree it could do a better job at this) is that the signature is matching the public key, so that the person who own the public key really did sign the binary. So it is all good.

What gpg tries to tell you more (again it ought to be improved) is that this signature by Thomas Orozco is not trusted, meaning no third party (including you) that you (your gpg) trust has signed this new signature and therefore gpg cannot verify its origin.

**Comment by jwmarshall** [comment]
Yes, sorry for my simple language. I looked up the source of the warning and then closed my issue. Thank you for your reply though! :)
