### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by tgeliot** [krallin/tini#121]
I find several shell scripts (including ddist.sh and run_tests.sh) but nothing that tells me how I should build the source.  These scripts seem to assume that I'll have environment variables ARCH_NATIVE and/or ARCH_SUFFIX set, but I'm given no clue as to what they're supposed to be.  In places in the scripts it appears that the script is prepared for these to not be set, but if I run ddist.sh with neither set, it fails with "Built cross package, but  is empty!"
Eventually I guessed and set both ARCH_NATIVE and ARCH_SUFFIX to "amd64", and that seems to work.

It would be nice to have better instructions on how to build this.

**Comment by krallin** [comment]
Have you tried following the build instructions in the README? 

> If you'd rather not download the binary, you can build Tini by running `cmake . && make`.

https://github.com/krallin/tini#building-tini

**Comment by krallin** [comment]
I should mention that you can also build out of tree (which is a little cleaner with Cmake), e.g. using:

```
cmake -B/tmp/tini-build/ -H. && pushd /tmp/tini-build && make && popd
```

**Comment by tgeliot** [comment]
@krallin > . . . running cmake . && make
My Redhat Linux VM doesn't have cmake by default, and the ddish.sh script is very clearly set up to build a Docker and then run ci/run_build.sh inside the Docker.  The resulting Docker image does have cmake.  Clearly someone believed that this was the best way to do it; they must have had a reason.  But that approach fails as I described.

**Comment by krallin** [comment]
@tgeliot,

> My Redhat Linux VM doesn't have cmake by default

Tini requires CMake to build from source. If you don't want to install CMake, then you can't build Tini. 

You're trying to get around this problem by using build scripts that were designed for a different purpose, which is the root cause of your difficulties here.

> the ddish.sh script is very clearly set up to build a Docker and then run ci/run_build.sh inside the Docker

Yes, and as the name implies (notably: `ci`), this script is used in CI. It allows for two things:

- Cross-platform builds
- Running tests

If your use case is "build Tini locally", then those scripts aren't the answer.

> Clearly someone believed that this was the best way to do it; they must have had a reason. 

You're seeing those scripts and concluding that someone believes they are the best way to build Tini. Let me stop you right there:

- That someone is me (so presumably I know why i wrote them)
- As I mentioned earlier, those scripts are the best way to do cross-platform builds and run tests.

Simply put: those scripts are NOT the best way to just build Tini locally: the best way to build Tini locally is to use `cmake . && make`.
 
> But that approach fails as I described.

The reason it fails is because you chose to use scripts that are meant to perform cross-platform builds and run tests when what you actually want to do is just build Tini locally.

---

To summarize: if you want to build Tini, then install the build tools you need to build Tini. If you won't do that, then you won't be able to build Tini.

If you'd rather try to use unrelated build scripts and coerce them into doing what you're trying to do (which is _possible_ albeit not recommended), then you should be prepared for them to fail: after all, that's not what they're designed to do.

And if you really don't want to install CMake (that's your call), then build your own Docker container with CMake in it and build Tini there.

**Comment by krallin** [comment]
In any case, if you absolutely want to use those scripts to build a local Tini, then the right command will be:

```shell
ARCH_NATIVE=1 ./ddist.sh
```

The resulting build artifacts will be located in `./build`

**Comment by tgeliot** [comment]
OK. Thanks, I didn't get that those scripts were intended for just CI.
