### ISSUE TITLE
incorrect usage

### ISSUE THREAD

**Issue by zhangyoufu** [krallin/tini#132]
I don't know if I understand the argument parsing correctly.

Should
`"Usage: %s [OPTIONS] PROGRAM -- [ARGS] | --version\n\n"`
be
`"Usage: %s [OPTIONS] -- PROGRAM [ARGS] | --version\n\n"`
?

According to README.md, `ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]` was used to call an existing entrypoint. This doesn't match the usage string.

**Comment by krallin** [comment]
The double dashes mean “end of option arguments, everything after is positional arguments”.

This matters in Tini and any other wrapper where you might be passing Tini arguments to proxy to another program to avoid a situation where the wrapper (Tini) might consume the other program’s arguments.

For example, if you do `tini foo -v`, then it’s ambiguous who should process the -v argument. 

POSIX says Tini should consider -v to be a positional argument because option arguments aren’t allowed after positional arguments (which means Tini should pass it as is to the child program). 

However, GNU libc disagrees, and allows option arguments after positional arguments (because it’s very convenient). Since GNU libc is the most widely distributed libc,  most people’s expectations align with GNU libc’s behaviour, not POSIX.

But, obviously, there are cases where you do want your option argument to be treated as a positional argument. In my earlier example, of you want to call foo with -v, then Tini needs to not consider this as a positional argument.

On strict POSIX libcs, that will implicitly be the case since -v is after a positional argument. On GNU libc, it won’t. 

To fix this, you use the double dashes. As long as they’re in front of the -v argument, then that argument will be deemed positional (and Tini won’t process it for itself). 

So, back to your question: since the program is a positional argument, it doesn’t really matter whether it’s before or after the double dashes, since the double dashes only have an effect on subsequent option arguments. To be specific, on a strict POSIX libc, the double dashes are redundant regardless of their position after the program, and on GNU libc, they will have the intended effect regardless of their position.

---

All that being said, the USAGE is arguably "more correct", but it's also a little bit less user-friendly. 

Consider this:

```
ENTRYPOINT ["/tini", "/docker-entrypoint.sh", "--"]
```

I guess it's not obvious where you're supposed to put the arguments for Tini and where you are supposed to put the arguments for your program.

**Comment by zhangyoufu** [comment]
If I wrote `ENTRYPOINT ["/sbin/tini", "/entrypoint.sh", "--"]`, `"--"` was passed to the child which is obviously incorrect.
