### ISSUE TITLE
how to run two multiple scripts using tini 

### ISSUE THREAD

**Issue by daparthi001** [krallin/tini#149]
i want to run script entrypoint.sh with tini and also run my backup script to just schedule my job ?How can  i do that ?

NTRYPOINT  [ "/opt/opendj/docker-entrypoint.sh" ]

CMD ["start"]

CMD ["chmod 755 /opt/opendj/scripts/schedule-backup.sh" && "exec tini -g -v  --  /opt/opendj/scripts/schedule-backup.sh"]

**Comment by yosifkit** [comment]
> All Tini does is spawn a single child (Tini is meant to be run in a container), and wait for it to exit all the while reaping zombies and performing signal forwarding.

So, `tini` will not follow or be involved in the process lifetime of anything started outside of its child (besides reaping the child's zombies).

I'd just use the host cron to run a new container (or does `docker exec`) to run a periodic backup script (or a "CronJob" if using Kubernetes).

**Comment by krallin** [comment]
@yosifkit  is spot-on here. Thanks!

**Comment by mitar** [comment]
I was inspired by tini but I also needed support for multiple programs to run inside a Docker container (like cron jobs because they are often bundled together with the main program), so I made another init system for Docker, [dinit](https://gitlab.com/tozd/dinit), which supports multiple processes and so you can have a cron daemon run in parallel with your main process.
