### ISSUE TITLE
Interactive Terminal / TTY Hangup

### ISSUE THREAD

**Issue by mattwilliamsnyc** [krallin/tini#19]
When using tini with a TTY, interactive shell commands like `python` and `irb` hang the terminal. Either of the following Dockerfiles will reproduce the issue (`python` can be replaced with `ruby`, etc.):

```dockerfile
FROM krallin/ubuntu-tini:trusty
RUN apt-get update && apt-get install -y --no-install-recommends python
```

```dockerfile
FROM debian:8.2

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates curl libc6 python && \
    curl -sSL "https://github.com/krallin/tini/releases/download/v0.8.0/tini" -o /usr/bin/tini && \
    chmod +x /usr/bin/tini && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/tini", "--"]
```

```bash
$ docker build -t tini-tty .
$ docker run --rm -it tini-tty python
```

Commenting out the `ENTRYPOINT` and rebuilding the image results in a working TTY session. Non-interactive commands, such as `$ docker run --rm -it tini-tty python --version` work just fine.

Am I missing something simple here like an option? Thanks!

**Comment by krallin** [comment]
Indeed, this isn't super surprising. Interactive mode isn't something I have considered as a goal so far (and thus not something I worked on).

Now, that doesn't mean it *shouldn't* be supported! If it's lightweight and doesn't make the tool harder to use, then it *should* be supported (one of the design goals of Tini *is* that adding it shouldn't break things that would otherwise work).

I'll try to get to the bottom of this and fix it (happy to hear suggestions!). 

Cheers,

**Comment by mattwilliamsnyc** [comment]
Thanks! This isn't a mission-critical requirement... I just wondered if I was missing something obvious. FWIW, here's the output of running w/ `-vvv`:

Running in `-vvv` mode shows the following (Interrupt is the result of Ctrl-C):

```bash
$ docker run --rm -it tini python
[INFO ] Spawned child process 'python' with pid '8'
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
[DEBUG] Passing signal: 'Window changed'
[TRACE] No child to reap
[DEBUG] Received SIGCHLD
[TRACE] No child to reap
[...]
```

**Comment by danilobuerger** [comment]
@mattwilliamsnyc just as a sidenote: you should check the hash of tini when curling it from github. See https://github.com/jenkinsci/docker/blob/master/Dockerfile for an example.

**Comment by mattwilliamsnyc** [comment]
@danilobuerger Thanks! That example is not how I'm installing tini. I was just trying to keep it small and to the point... but out of curiosity, where did you get the checksum?

**Comment by danilobuerger** [comment]
The first time you could just download it and do ``$ openssl dgst -sha1 tini``

**Comment by mattwilliamsnyc** [comment]
Ah, ok. I didn't know if this was published somewhere as an .asc or whatever. I have an update script that scrapes for the latest version and updates my base Dockerfiles:
```bash
curl -s https://github.com/krallin/tini/releases/latest | grep -o "/v.*\"" | sed 's:^..\(.*\).$:\1:'
```
I can do the hashing there and pin that as well. Thanks for the tip!

**Comment by krallin** [comment]
I eventually want to make this published somewhere (but right now the builds happen in Travis so it's not entirely trivial!)

**Comment by krallin** [comment]
Hey @mattwilliamsnyc,

I was able to reproduce the issue, and I think I have a fix for it in #21 

We introduced this as a side effect of #15 (tests didn't catch it, but now we have some that will).

The problem is that the foreground process group on the tty is Tini, not the child process group, which thus means the child process (Python in your example) hangs when it tries to write to tty / set settings.

In Python's case, this happens when the readline module is loaded (you can see that by running `python -vvv`). Python gets interrupted by `SIGTTOU`, which is also `tini` receives a `SIGCHLD` with nothing to reap in the log you sent over.

---

The solution in #21 is to have Tini make the child process group the new foreground process group (and to gracefully bail if there is no tty).

I want to test a few last things before I merge it, but I think I'll do that soon.

Cheers,

**Comment by krallin** [comment]
Oh, and I was about to forget: thanks a ton for the report!

**Comment by mattwilliamsnyc** [comment]
Hey @krallin,

Thanks for the explanation and the quick fix. I'll continue to report anything I encounter that doesn't match standard Docker behavior since that's a design goal.

Thanks again for the update and for all your work on this project!

**Comment by krallin** [comment]
All right, I fixed the concerns I had yesterday. Will probably merge and release a new version tomorrow!

**Comment by krallin** [comment]
@mattwilliamsnyc This should be fixed as of 0.8.2. I'm building new images and they should be live soon.

@danilobuerger since you're already in this thread ;). How do we get the Alpine packages updated to this new version? : )

**Comment by danilobuerger** [comment]
I dont mind to carry on maintaining this package for alpine. So best way for the future would be if you ping me here or via twitter when you want it updated.

**Comment by krallin** [comment]
Awesome; thanks @danilobuerger. I'll continue pinging you in issues when a release goes out then! : )

**Comment by jamshid** [comment]
Thanks for interactive / tty support! I was using dumb-init but had to switch because it doesn't support it (https://github.com/Yelp/dumb-init/issues/78).

**Comment by krallin** [comment]
Thanks @jamshid!
