### ISSUE TITLE
[Question]What's the difference between using tini and a shell script in a container

### ISSUE THREAD

**Issue by zjleon** [krallin/tini#45]
I new to docker and know nothing about linux commands. I read the README carefully but I can't understand what the benefit it will bring to me.
I used a shell script to start my node js server, what can I get from using tini instead?

**Comment by krallin** [comment]
@zjleon the answer depends on what your shell script does; and whether it uses `exec` when starting your NodeJS server. 

Can you post your shell script? I'd be able to provide a more accurate answer then :)

**Comment by zjleon** [comment]
@krallin thx for reply, 
this is my shell script to start the node server
```
// container.dev.web_static.initial.sh
npm install --prefix ./src/web_static
npm run dev:web_static
```

in the dockerfile, I just copy it to the container
```
ADD ./scripts/container.dev.web_static.initial.sh ./initial.sh
CMD ["bash", "./initial.sh"]
```

the shell script right now is real simple, I can't see too much benefit I can get from using tini(from what I learn from the README), Is that right?

**Comment by fiunchinho** [comment]
Using the shell script to start your node application will do that your application doesn't receive signals. So for example, if you run your container and then try to `docker stop` it, it will take 10 seconds, since Docker sends a `SIGTERM` to stop your container, but your container doesn't handle signals (because shell is the main process), so after 10 seconds Docker gives up and sends a `SIGKILL` to kill the container. Receiving a `SIGKILL` could lead to unexpected behaviour if you are running for example an HTTP server. Normally we stop servers using graceful shutdown, instead of just killing them.
It'll also happen if you try to `ctrl+c` your container. It won't stop.

This won't happen with Tini.
