### ISSUE TITLE
trapping SIGTERM when docker-compose kill rabbitmq

### ISSUE THREAD

**Issue by arthurtsang** [krallin/tini#6]
Hi Thomas,

The [official Rabbitmq docker image] (https://github.com/docker-library/rabbitmq/blob/bb91e64b5664a4ab5cd681b7501a2830edbe9ddf/docker-entrypoint.sh) is using tini to start rabbitmq.  (congrats on the adoption!)  I am trying to trap sigterm when the container is being killed.

```
function shutdown() {
        echo 'exiting - deregister from consul'
        curl http://$BRIDGE_IP:8500/v1/agent/service/deregister/$HOST
        exit 0
}
trap 'shutdown' SIGKILL SIGTERM SIGHUP SIGINT EXIT

tini -- ./docker-entrypoint.sh "$@"
```

i have my own script as entrypoint and call docker-entrypoint.sh from the official rabbitmq image.  

```
...
if [ "$1" = 'rabbitmq-server' ]; then
...
	chown -R rabbitmq /var/lib/rabbitmq
	set -- gosu rabbitmq tini -- "$@"
fi

exec "$@"
```

my shutdown function is never executed when i kill the container.  what am i missing here?  

Thanks,
--arthur

**Comment by krallin** [comment]
Hey @arthurtsang,

I'm not 100% sure this is a Tini issue, but I may be able to help you out. How are you killing the container? 

If you're simply using `docker kill ...`, then this issues a `SIGKILL`, which exits immediately and won't let your handler run. Using the `--signal=TERM` might solve  your issue.

---

Now, note that using Tini is a bit redundant in your case. The stated goal of Tini is to reap zombies all the while doing proper signal handling. To that end, Tini must run as PID 1 within your container, so that zombies get re-parented to it.

This will eventually become optional in Tini (by registering Tini as a child subreaper), but that wouldn't really help you either: since you're running bash as PID 1, you already get zombie reaping (Bash does that out of the box), but not signal forwarding (which Bash doesn't do, which is why Tini was created in the first place). 

Since your signals are all stuck in bash, they don't make their way to Tini, and they don't make their way to RabbitMQ either (which means RabbitMQ cannot be terminated gracefully, which is bad).

----

If I were you, I'd try to address this problem outside of the container, by listening on the `/events` stream of the Docker API (see [here](https://docs.docker.com/reference/api/docker_remote_api_v1.20/)). I think this would be:

+ More robust, since it'll work even if the container isn't gracefully terminated (i.e. receives a `SIGKILL`).
+ More generic, since you'll be able to use the same code to watch all your containers.

Hope this helps,

Cheers,

**Comment by arthurtsang** [comment]
Thanks a lot.  great info!  i'll pass on the SIGTERM in the shutdown function and looks into the events stream api.
