### ISSUE TITLE
It would be really, really nice to have an option to map certain exit code to 0

### ISSUE THREAD

**Issue by nixx** [krallin/tini#69]
The rationale is the use of Tini together with software that is not able to exit cleanly when terminated with SIGINT, as is the case for the JVM.

When a JVM gets a SIGINT, it runs all shutdownhooks, and then exits with 128 + SIGINT (143). When running on OpenShifts for instance, this will give an error in the UI.

It could always be fixed within a bash-script or something alike, but that is not easy to get right.

**Comment by nixx** [comment]
I did a shot at it here:

https://github.com/nixx/tini/commit/37826b8413722b9fcc9f7b6081f2da927502d3af

I won't make a pull request, since I'm not even close to write good enough C.

**Comment by krallin** [comment]
I think this is reasonable to add as long as I can keep the implementation minimal (in fact I've run into exactly this issue myself with Elasticsearch).

I'm not a huge fan of parsing an ENV variable for this, and I'd rather for this to be a CLI flag (for now I've reserved ENV vars for things that you'd want to be able to configure even if you're not directly writing the code that starts Tini).

Implementation-wise, I'm probably going to rely on a bitfield representing all possible exit codes and whether they should be re-mapped to 0. This will avoid dynamic memory allocation, and use very little memory overall (we only need 256 bits total to represent this).

**Comment by krallin** [comment]
Still a bit of polishing to do, but here's what I had in mind: https://github.com/krallin/tini/commit/expect-status-code You'd use the `-e` flag to ignore a given exit code.

**Comment by ghaiklor** [comment]
@nixx @krallin we've faced the same issue, but with Marathon and Kubernetes.

Our Java component runs as a daemon, listens for messages from RabbitMQ and processes them. Everything works great, except the case, when we need to stop this daemon via deleting the Pod. As we know, orchestrator triggers SIGTERM in such cases and waits for process dies.

The problem is that JVM handles SIGTERM and exits with code 128 + 15 (SIGTERM) = 143 which is not 0, obviously. So, Kubernetes decides to start this Pod again (backoff), thinking that the last time process died abnormally.

My question here is, do you have any plans on merge the PR which allows to map exit codes to 0?
Or, there is another solution for such cases?

**Comment by krallin** [comment]
Yes, I'm planning to merge it. I've just been a little busy lately and haven't had enough time to dedicate to Tini, but I'll be doing a release soon including #75 and #107.

**Comment by drobiazko** [comment]
@krallin this are awesome news. Kudos to you for maintaining this project even after it was included in Docker itself. Do you have an ETA for the release?

**Comment by krallin** [comment]
Probably this week. That said, if you have an urgent need to use either of these features, building Tini yourself is not particularly complex (and [documented in the README](https://github.com/krallin/tini#building-tini)).
