### ISSUE TITLE
Feature request - reload?

### ISSUE THREAD

**Issue by djMax** [krallin/tini#71]
I know this is probably a pretty contentious topic. But I would find it immensely useful if there was some way to tell tini "I don't want the container to end, but I would like you to restart the main child process now."

Is there any way to do this or to safely layer something in that will?

**Comment by krallin** [comment]
This does feel overly out of scope (I'm sorry!), mainly because restarting the child isn't a very well defined operation, and seems to me like something that should be left to a more complete process management system like Supervisord, which should do exactly this when you send it SIGHUP (perhaps you'd want with Tini sitting in front of it to handle zombie reaping).

That being said, if you can have your child respond to something like the USR1 signal to restart itself, Tini can properly forward it. That's a more lightweight solution than using e.g. Supervisord.

**Comment by djMax** [comment]
Thanks, makes sense. The tricky bit is that intermediate process also has to do what tini does re: signal forwarding. But yes, I want cake and I want to eat it to. Thanks for the response!

**Comment by kbulygin** [comment]
@krallin I have a similar case. Thanks for suggesting Supervisor. It looks like the right tool indeed, despite that it's a bit heavy. Just a minor note regarding ["perhaps you'd want with Tini sitting in front of it to handle zombie reaping"](https://github.com/krallin/tini/issues/71#issuecomment-272652178): Supervisor itself seems to have this feature [since 2006](https://github.com/Supervisor/supervisor/blob/f7781eb907bb13bf0eb8b82ad12e9774c1448d9a/src/supervisor/supervisord.py#L619). Like with Tini, one has to be careful to run it with PID 1 though.
