### ISSUE TITLE
How can i receive signal in the jvm?

### ISSUE THREAD

**Issue by VFT** [krallin/tini#72]
I use /bin/bash to run jvm as a child process, but i can't receive signal in the jvm.

`Dockerfile`:
```bash
ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]
```

and `docker-entrypoint.sh`:
```bash
#!/bin/bash

source `dirname $0`/init-product.sh

if [ -z "$POOL_TYPE" ]; then
  source `dirname $0`/init.sh $RESOURCE_ID
  echo "****FINISHED****"
else
  echo "****FINISHED****"
  java -Xmx64m -Xms16m -Xmn8m -Xss1m -XX:ReservedCodeCacheSize=5m -XX:NewRatio=3 -jar /usr/local/agent/agent-1.0.1.jar $POOL_TYPE
fi
```

**Comment by krallin** [comment]
tini proxies signals to its immediate child (bash in this case), but bash does not, so your entrypoint  breaks signal forwarding here (the JVM is a child of bash, not tini).

The solution is to ensure you don't leave a bash shell between Tini and the JVM. You can do so by replacing 

`java -Xmx64m -Xms16m ...`

With:

`exec java -Xmx64m -Xms16m ...` 

Using `exec` ensures that the bash shell (i.e. tini child) replaces itself with the JVM (rather than spawn the JVM as a child), so that it receives the signals tini sends to it.

---

Note that if your also spawn a JVM in your `if [ -z "$POOL_TYPE" ]; then` branch, you might have to make some changes to your `init.sh` script.

**Comment by VFT** [comment]
@krallin  Thanks for your guide,it is worked.
