### ISSUE TITLE
tini doesn't like if SIGTERM in a child takes some time

### ISSUE THREAD

**Issue by mattdodge** [krallin/tini#78]
I'll give you the gist of what I'm seeing first, then provide code examples. Basically, my `CMD` in my `Dockerfile` runs a bash script which at some point will launch a python web server. This server is set up to listen for `SIGINT` and `SIGTERM` and then shut down gracefully if it receives either of those. However, when I pass `SIGTERM` (via `docker stop` or `docker kill -s TERM`), tini passes it down properly but doesn't give it any time to clean up, it just exits the process immediately.

Ok, now for some examples, 3 files involved:

**sig_handle.py**
```python
import sys
from time import sleep
import signal


def handler(signum, frame):
    if signum == 15:
        print("waiting after SIGTERM")
        sleep(3)
    elif signum == 2:
        print("waiting after SIGINT")
        sleep(3)
    print("----- IN PROGRAM Got Signal {}".format(signum))
    sys.exit()

catchable_sigs = set(signal.Signals) - {signal.SIGKILL, signal.SIGSTOP}
for sig in catchable_sigs:
    signal.signal(sig, handler)

while True:
    sleep(1)
```

**sig_bash.sh**
```bash
python sig_handle.py
```

**Dockerfile**
```Dockerfile
FROM python:3.5

ENV TINI_VERSION v0.14.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "-g", "-vv", "--"]

ADD sig_bash.sh /sig_bash.sh
ADD sig_handle.py /sig_handle.py

CMD ["/bin/bash", "/sig_bash.sh"]
```

If I run a container and pass it `SIGINT` I get what I'd expect, the handler catches it, waits 3 seconds, prints the IN PROGRAM message and then exits.
```
docker run -it --name c_tinitest tinitest
docker kill -s INT c_tinitest
```

container output:
```
c_tinitest
[INFO  tini (1)] Spawned child process '/bin/bash' with pid '7'
[DEBUG tini (1)] Passing signal: 'Interrupt'
waiting after SIGINT
----- IN PROGRAM Got Signal 2
[DEBUG tini (1)] Received SIGCHLD
[DEBUG tini (1)] Reaped child with pid: '7'
[INFO  tini (1)] Main child exited normally (with status '0')
```

However, if I run the `docker kill` with `TERM` instead, it doesn't do any waiting. Sometimes I'll see my program say "waiting after SIGTERM" but sometimes it says nothing (likely a race condition). 

container output:
```
c_tinitest
[INFO  tini (1)] Spawned child process '/bin/bash' with pid '7'
[DEBUG tini (1)] Passing signal: 'Terminated'
waiting after SIGTERM
[DEBUG tini (1)] Received SIGCHLD
[DEBUG tini (1)] Reaped child with pid: '7'
[INFO  tini (1)] Main child exited with signal (with signal 'Terminated')
```

Is `SIGTERM` treated any differently than other signals? It seems since this is the signal sent by `docker stop` it should allow some time to do some cleanup.

**Comment by krallin** [comment]
No, Tini does not make any assumptions about the meaning of the signal it receives and forwards to its child.

The only signal-specific handling in Tini is a set of signals that are _not_ passed on to its child: https://github.com/krallin/tini/blob/6ad9813ed8864150774c9ec3672b5b713b6b2902/src/tini.c#L356, but neither`SIGTERM` nor `SIGINT` are in this list.

It's most likely that Bash is the one with signal-specific handling here: when Tini proxies `SIGTERM` to its child, that child is Bash, and Bash decides what to do with the signal. In this case, it looks like it's respectively proxying `SIGINT` to your Python script and exiting upon `SIGTERM`. 

The best approach here would be to remove the middleman (Bash) when you no longer need it. Assuming spinning up your Python web server is the last thing you do in your Bash script, this is trivial.

Just rewrite `sig_bash.sh` as is:

```
#!/bin/bash

# What you have already
do one thing
do another thing

# The exec part is what maters here
exec python sig_handle.py
```

Here, using `exec` means "replace my Bash shell with Python". This does mean you *cannot* run *anything* in the Bash script after you call `exec`, but that's probably OK since your Python script is presumably able to cleanup after itself in its own signal handlers.

Now, the effect of using `exec` here is that, you'll have a process hierarchy that looks like `Tini -> Python` as opposed to `Tini -> Bash -> Python`, so when Tini proxies a signal to its child, that's no longer Bash: it's your Python process. This means your Python script will receive signals directly, and will be free to handle them however it sees fit.

---

See for essentially the same issue https://github.com/krallin/tini/issues/72

Cheers,

**Comment by mattdodge** [comment]
Gah, I looked for a duplicate issue and couldn't find one! Sorry about that.

But thank you very much for the explanation. You're spot on, it was the way bash handled `SIGTERM`. Your suggestion worked great. Not only did it fix my problem, but I learned the behavior of bash `exec` in the process!

**Comment by krallin** [comment]
> Gah, I looked for a duplicate issue and couldn't find one! Sorry about that.

No problem :)

> But thank you very much for the explanation. You're spot on, it was the way bash handled `SIGTERM`. Your suggestion worked great. Not only did it fix my problem, but I learned the behavior of bash `exec` in the process!

Happy to help!
